#!/bin/env bash

LIBSQL_AUTH_TOKEN="${TURSO_DB_TOKEN:-$AUTH_TOKEN}"

if [ -z "$LIBSQL_AUTH_TOKEN" ]; then
    echo "Missing TURSO_DB_TOKEN or AUTH_TOKEN environment variable"
    exit 1
fi

command=("${@:1}")

case "${command[0]}" in
    db)
        if [ "${command[1]}" == "shell" ]; then
            cmd="turso db shell \"$(echo \"${command[2]}?authToken=${LIBSQL_AUTH_TOKEN}\")\""
            eval "$cmd"
        fi
        ;;
    *)
        echo "Command not found"
        ;;
esac

