#!/bin/env bash

LIBSQL_AUTH_TOKEN="${TURSO_DB_TOKEN:-$AUTH_TOKEN}"

command=("${@:1}")

case "${command[0]}" in
    db)
        if [ "${command[1]}" == "shell" ]; then
            if [ -n "${LIBSQL_AUTH_TOKEN:-}" ]; then
                cmd="turso db shell \"$(echo \"${command[2]}?authToken=${LIBSQL_AUTH_TOKEN}\")\""
                eval "$cmd"
            else
                cmd="turso db shell \"$(echo \"${command[2]}\")\""
                eval "$cmd"
            fi
            unset LIBSQL_AUTH_TOKEN
        fi
        ;;
    *)
        echo "Command not found"
        ;;
esac

unset LIBSQL_AUTH_TOKEN

